`r paste0('# ', measure_item, '{data-navmenu=', str_to_sentence(menu_theme), '}')`

Column {data-width=600}
-----------------------------------------------------------------------

### 
```{r plot}
plot <- ggplot(subpage_data, aes_string(fill = as.name(measure_item))) +
  geom_sf(alpha = 0.8, colour = 'white', size = 0.3) +
  geom_text(data = subpage_data, aes(X, Y, label = asc_name), size = 3) +
  labs(x = NULL, y = NULL) +
  theme(line = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        panel.background = element_blank(),
        legend.position = "top",
        legend.title = element_text(size = 9),
        legend.text = element_text(size = 8))

# Apply more formatting depending on the type of measure
if (!is.na(measure_type)){
  if (measure_type == "percentage"){
    plot <- plot +
        scale_fill_viridis(discrete = FALSE,
                     name = measure_item,
                     direction = -1,
                     labels = function(x) percent(x, accuracy = 1, scale = 1),
                     guide = guide_colourbar(
                       direction = "horizontal",
                       barheight = unit(2, units = "mm"),
                       barwidth = unit(50, units = "mm"),
                       draw.ulim = F,
                       title.position = 'top',
                       title.hjust = 0.5,
                       label.hjust = 0.5)) 
  } else if (measure_type == "small percentage"){
    plot <- plot +
        scale_fill_viridis(discrete = FALSE,
                     name = measure_item,
                     direction = -1,
                     labels = function(x) percent(x, accuracy = 0.1, scale = 1),
                     guide = guide_colourbar(
                       direction = "horizontal",
                       barheight = unit(2, units = "mm"),
                       barwidth = unit(50, units = "mm"),
                       draw.ulim = F,
                       title.position = 'top',
                       title.hjust = 0.5,
                       label.hjust = 0.5)) 
  } else if (measure_type == "integer"){
          plot <- plot +
        scale_fill_viridis(discrete = FALSE,
                     name = measure_item,
                     direction = -1,
                     labels = function(x)
                       format(x, big.mark = ","),
                     guide = guide_colourbar(
                       direction = "horizontal",
                       barheight = unit(2, units = "mm"),
                       barwidth = unit(50, units = "mm"),
                       draw.ulim = F,
                       title.position = 'top',
                       title.hjust = 0.5,
                       label.hjust = 0.5)) 
  }
}

# Display the plot
plot
```

Column {data-width=400}
-----------------------------------------------------------------------

### {data-height=550}

```{r table}
# Reorganise data frame before formatting as (DT) table
subpage_data <- subpage_data %>% 
  as_tibble () %>% #drops sf geometry (but not geom column)
  select(-objectid, -X, -Y, -geom) %>% 
  relocate(asc_name, .before = 1) %>%
  relocate(ca_name, .before = ca_number) %>% 
  relocate(all_of(measure_item), .before = 1)

# The DT percentage formatting assumes 0.1 is 10%
if (!is.na(measure_type)){
  if (measure_type == "percentage" || measure_type == "small percentage"){
    subpage_data[, 1] <- (subpage_data[, 1] / 100)
  }
}

# Apply some table formatting
subpage_data <- subpage_data %>% 
  rename(ASC = asc_name, "CA number" = ca_number, "CA name" = ca_name) %>%
  datatable(rownames = FALSE,
            style = "bootstrap",
            class = "compact",
            options = list(dom = 't', orderClasses = TRUE))

# Apply more formatting depending on the type of measure
if (!is.na(measure_type)){
  if (measure_type == "percentage"){
    subpage_data <- formatPercentage(subpage_data, 1, 1)
  } else if (measure_type == "small percentage"){
    subpage_data <- formatPercentage(subpage_data, 1, 2)
  } else if (measure_type == "integer"){
    subpage_data <- formatRound(subpage_data, 1, 0)
  }
}

# Display the formatted table
subpage_data
```

### {data-height=450}

```{r meta}
subpage_metadata %>% 
  kbl(col.names = NULL) %>% 
  scroll_box(width = "400", height = "400")
```
