---
title: "ASC locality insight"
output: 
  flexdashboard::flex_dashboard:
    theme: paper
    logo: scc-60px.png
    navbar:
      - { title: "data via Local Insight",  icon: "fa-database", href: "https://sheffield.communityinsight.org/", align: right }
      - { title: "source code",  icon: "fa-github", href: "https://github.com/scc-pi/asc-localities-insight", align: right }
---

```{r setup, include=FALSE}
library(tidyverse); library(readxl); library(sf) 
library(flexdashboard); library(viridis); library(scales)
library(DT); library(gt); library(ggrepel)

# Disable use of scientific notation
options(scipen=999)

# Define a theme for the plots in the dashboard 
theme_set(theme_minimal())

## FUNCTIONS -------------------------------------------

# Alternative to the scales dollar function so the prefix is £ rather than $
pound <- function(x, y) {
  dollar(round(x, digits = 0), prefix = "£")
}

# Alternative to the DT currency function so the prefix is £
formatPound <- function(x, y, z) {
  formatCurrency(table = x, columns = y, digits = 0, currency = "£")
}
```

```{r global, include=FALSE}

## LOCAL VARIABLES -------------------------------------------

# Name of the SLI measures spreadsheet
sli_measures_file <- "sli_measures.xlsx"

# Location of data we're using for maps
map_data_folder <- str_c(
  "S:/Public Health/Policy Performance Communications/Business Intelligence/",
  "Projects/AdultSocialCare/ASC_SNA/data")

# Name of the ASC SLI data file
asc_sli_file <- "df_asc_sli.rds"

# Name of the file with the ASC locality boundaries
asc_localities_sf_file <- "sf_asc_localities.rds"

# Name of the file with the SLI metadata
sli_measure_with_meta_file <- "df_sli_measure_with_meta.rds"

## READ & TRANSFORM ------------------------------------------

# Get the names of the ASC SLI measures that we want to include
df_asc_sli_measures <- read_xlsx(sli_measures_file) %>% 
  filter(str_to_lower(include) == "yes") %>% 
  select(-include)

# Get the ASC SLI data
df_asc_sli <- read_rds(str_c(map_data_folder, "/", asc_sli_file)) %>% #all
  filter(measure %in% df_asc_sli_measures$measure) %>% #only what we want
  pivot_wider(names_from = measure, values_from = value)

# Get the ASC locality boundaries with cross-references to LACs
sf_asc_localities <- read_rds(str_c(map_data_folder,
                                    "/", asc_localities_sf_file))

# Join the SLI data to the ASC locality boundaries
sf_asc_sli <- left_join(sf_asc_localities, df_asc_sli, 
                        by = c("ca_name" = "area")) %>% 
  relocate(c(X, Y), .before = geom)

# Get the metadata
df_sli_measure_with_meta <- read_rds(str_c(map_data_folder, "/", 
                                           sli_measure_with_meta_file)) %>% 
  filter(measure %in% df_asc_sli_measures$measure) %>% 
  select(-include) %>% 
  pivot_longer(!c(theme, measure), 
               names_to = "meta_attr", values_to = "meta_value")
```

```{r render-subpages, include=FALSE}
# Create variable which stores all subpages outputs
out = NULL

# Set knitr options to allow duplicate labels (needed for the subpages)
options(knitr.duplicate.label = 'allow')

# Create temporary environment which we use for knitting subpage.RMD
subpage_env <- new.env()

# Get list of unique themes
df_themes <- df_asc_sli_measures %>% 
  select(theme) %>% 
  unique()

# Provide a menu header for each theme
for (menu_theme in df_themes$theme) {
  
  # Filter data on theme
  sf_asc_sli_theme <- sf_asc_sli %>% 
    filter(theme == menu_theme)
  
  # Filter measures on theme
  df_asc_sli_measures_theme <- df_asc_sli_measures %>% 
    filter(theme == menu_theme)

  # Provide a menu item for each measure
  for (measure_item in df_asc_sli_measures_theme$measure) {
    
    # Filter for the measure
    df_measure_filtered <- df_asc_sli_measures %>% 
      filter(theme == menu_theme & measure == measure_item)
    
    # Get the type of measure e.g. currency
    measure_type <- df_measure_filtered %>% 
      select(type) %>% 
      pluck(1) %>% 
      str_to_lower() %>% 
      str_trim()
    
    # Get the number of decimal places for the measure
    measure_decimals <- df_measure_filtered %>% 
      select(decimals) %>% 
      pluck(1)
    
    # Filter metadata for the measure 
    df_metadata <- df_sli_measure_with_meta %>% 
      filter(theme == menu_theme & measure == measure_item) %>% 
      select(-theme, -measure) %>% 
      pivot_wider(names_from = meta_attr, values_from = meta_value)
    
    # Have we got any metadata for this measure?
    got_metadata <- df_metadata %>%
      drop_na %>% 
      count() > 0
    
    # Craft a data frame of formatted metadata
    if (got_metadata){
      subpage_metadata <- tribble(~meta) %>% 
        add_row(meta = df_metadata$description) %>%
        add_row(meta = str_c("**Date:** ", df_metadata$date)) %>%
        add_row(meta = str_c("**Update frequency:** ",
                             df_metadata$update_frequency)) %>%
        add_row(meta = str_c("**Source:** ", df_metadata$source)) %>%
        add_row(meta = ifelse(!is.na(df_metadata$url),
                              str_c("[", str_replace(df_metadata$url,
                                                     "https://", ""),
                                    "](", df_metadata$url, ")"),
                              ""))
    } else { #or not
      subpage_metadata <- tribble(~meta, "*No metadata.*") 
    }
    
    # Filter data for the measure 
    subpage_data <- sf_asc_sli_theme %>% 
      select(1:4, all_of(measure_item), c(X, Y, geom))
    
    # The ggplot & DT percentage formatting assumes 0.1 is 10%
    if (!is.na(measure_type)){
      if (measure_type == "percentage"){
        subpage_data <- relocate(subpage_data, all_of(measure_item), .before = 1) 
        subpage_data[, 1] <- (subpage_data[, 1] / 100)
      }
    }

    # Assign filtered data, theme & measure, and metadata to subpage_env
    assign("subpage_data", subpage_data, subpage_env)
    assign(menu_theme, measure_item, subpage_env)
    assign("measure_type", measure_type, subpage_env)
    assign("subpage_metadata", subpage_metadata, subpage_env)

    # Knit subpage.RMD using the subpage_env and add result to out vector
    out = c(out, knitr::knit_child('asc_sli_subpage.Rmd',
                                   envir = subpage_env))
  }
}
```

`r paste(knitr::knit_child(text = out), collapse = '')`